# Generated by Django 2.0.4 on 2018-04-30 06:26

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackendTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_members', jsonfield.fields.JSONField(default=[])),
            ],
        ),
    ]
